# This file is automatically generated for code intellisense only.
# It does not reflect the actual implementation.

from __future__ import annotations
from collections.abc import Iterator

from . import core

class BaseDocumentTypes():
    """
    !!!!! Warning !!!!!
    ! This is in preview state; please see the help for more info
    !!!!! Warning !!!!!
    
    Specifies the base document option for drawing creation.
    """
    def __init__(self):
        pass
    FromScratchBaseDocumentType = 0
    FromTemplateBaseDocumentType = 1

class CenterLineDisplayTypes():
    """
    !!!!! Warning !!!!!
    ! This is in preview state; please see the help for more info
    !!!!! Warning !!!!!
    
    Center line display options for cylindrical features.
    """
    def __init__(self):
        pass
    OffCenterLineDisplayType = 0
    AllCylindricalCenterLineDisplayType = 1
    AllHolesCenterLineDisplayType = 2

class CenterMarkDisplayTypes():
    """
    !!!!! Warning !!!!!
    ! This is in preview state; please see the help for more info
    !!!!! Warning !!!!!
    
    Center mark display options for circular features.
    """
    def __init__(self):
        pass
    OffCenterMarkDisplayType = 0
    AllHolesCenterMarkDisplayType = 1
    AllFilletsCenterMarkDisplayType = 2
    AllCircularEdgesCenterMarkDisplayType = 3
    AllPunchesCenterMarkDisplayType = 4

class DefaultOriginTypes():
    """
    !!!!! Warning !!!!!
    ! This is in preview state; please see the help for more info
    !!!!! Warning !!!!!
    
    Default origin (datum) point for component dimension placement.
    """
    def __init__(self):
        pass
    ModelOriginDefaultOriginType = 0
    BottomLeftDefaultOriginType = 1
    BottomRightDefaultOriginType = 2
    TopLeftDefaultOriginType = 3
    TopRightDefaultOriginType = 4

class DimensionStrategyTypes():
    """
    !!!!! Warning !!!!!
    ! This is in preview state; please see the help for more info
    !!!!! Warning !!!!!
    
    Dimension placement strategy for automatic dimensioning.
    """
    def __init__(self):
        pass
    OverallDimensionStrategyType = 0
    AutomaticDimensionStrategyType = 1
    BaselineDimensionStrategyType = 2
    ChainDimensionStrategyType = 3

class DrawingContentTypes():
    """
    !!!!! Warning !!!!!
    ! This is in preview state; please see the help for more info
    !!!!! Warning !!!!!
    
    Specifies which assembly content is used when creating automatic drawing sheets (API supports
    Full Assembly and Visible Only mode).
    """
    def __init__(self):
        pass
    FullAssemblyDrawingContentType = 0
    VisibleOnlyDrawingContentType = 1

class DrawingCreationModes():
    """
    !!!!! Warning !!!!!
    ! This is in preview state; please see the help for more info
    !!!!! Warning !!!!!
    
    Specifies the mode of drawing creation.
    """
    def __init__(self):
        pass
    AutomaticDrawingCreationMode = 0
    ManualDrawingCreationMode = 1

class DrawingStandardTypes():
    """
    !!!!! Warning !!!!!
    ! This is in preview state; please see the help for more info
    !!!!! Warning !!!!!
    
    Specifies the different drawing standards that can be used.
    The standard defines projection angle, dimension styles, title block format, and annotation conventions.
    """
    def __init__(self):
        pass
    ISODrawingStandardType = 0
    ASMEDrawingStandardType = 1

class DrawingUnitTypes():
    """
    !!!!! Warning !!!!!
    ! This is in preview state; please see the help for more info
    !!!!! Warning !!!!!
    
    Specifies the different drawing units that can be used.
    The unit type affects dimension display, annotations, and measurements throughout the drawing.
    """
    def __init__(self):
        pass
    InchDrawingUnitType = 0
    MillimeterDrawingUnitType = 1

class DrawingViewStyleTypes():
    """
    !!!!! Warning !!!!!
    ! This is in preview state; please see the help for more info
    !!!!! Warning !!!!!
    
    Visual rendering style for drawing views.
    """
    def __init__(self):
        pass
    VisibleEdgesDrawingViewStyleType = 0
    VisibleAndHiddenEdgesDrawingViewStyleType = 1
    ShadedDrawingViewStyleType = 2
    ShadedWithVisibleEdgesDrawingViewStyleType = 3

class HolePreferencesTypes():
    """
    !!!!! Warning !!!!!
    ! This is in preview state; please see the help for more info
    !!!!! Warning !!!!!
    
    Hole and thread annotation preferences.
    """
    def __init__(self):
        pass
    HoleAndThreadNoteHolePreferencesType = 0
    HoleNoteOnlyHolePreferencesType = 1
    ThreadNoteOnlyHolePreferencesType = 2
    NoHoleAnnotationsHolePreferencesType = 3

class PDFSheetsExport():
    """
    The various options that define which sheets to print.
    """
    def __init__(self):
        pass
    AllPDFSheetsExport = 0
    SelectedPDFSheetsExport = 1
    CurrentPDFSheetExport = 2
    RangePDFSheetsExport = 3

class SheetCreationTypes():
    """
    !!!!! Warning !!!!!
    ! This is in preview state; please see the help for more info
    !!!!! Warning !!!!!
    
    Specifies which components get drawing sheets generated.
    """
    def __init__(self):
        pass
    FirstLevelOnlySheetCreationType = 0
    AllLevelsSheetCreationType = 1

class SheetOrientationTypes():
    """
    !!!!! Warning !!!!!
    ! This is in preview state; please see the help for more info
    !!!!! Warning !!!!!
    
    Specifies the sheet orientation for printing and display.
    """
    def __init__(self):
        pass
    LandscapeSheetOrientationType = 0
    PortraitSheetOrientationType = 1

class SheetSizes():
    """
    !!!!! Warning !!!!!
    ! This is in preview state; please see the help for more info
    !!!!! Warning !!!!!
    
    Specifies the sheet size for a drawing document.
    """
    def __init__(self):
        pass
    CustomSizeSheetSize = 0
    A4ISOSheetSize = 1
    A3ISOSheetSize = 2
    A2ISOSheetSize = 3
    A1ISOSheetSize = 4
    A0ISOSheetSize = 5
    AASMESheetSize = 6
    BASMESheetSize = 7
    CASMESheetSize = 8
    DASMESheetSize = 9
    EASMESheetSize = 10

class TableLocationTypes():
    """
    !!!!! Warning !!!!!
    ! This is in preview state; please see the help for more info
    !!!!! Warning !!!!!
    
    Corner location options for tables on sheets. Used for parts lists, bend tables, and other sheet tables.
    """
    def __init__(self):
        pass
    TopLeftTableLocationType = 0
    TopRightTableLocationType = 1
    BottomLeftTableLocationType = 2
    BottomRightTableLocationType = 3

class TangentEdgeDisplayTypes():
    """
    !!!!! Warning !!!!!
    ! This is in preview state; please see the help for more info
    !!!!! Warning !!!!!
    
    Tangent edge display options.
    """
    def __init__(self):
        pass
    OffTangentEdgeDisplayType = 0
    OnTangentEdgeDisplayType = 1
    ForeshortenedTangentEdgeDisplayType = 2

class AnimationPreferences(core.Base):
    """
    !!!!! Warning !!!!!
    ! This is in preview state; please see the help for more info
    !!!!! Warning !!!!!
    
    Preferences for animation/exploded view sheets. Enable via GlobalPreferences.generateAnimationSheet (default: false).
    """
    def __init__(self):
        pass
    @staticmethod
    def cast(arg) -> AnimationPreferences:
        return AnimationPreferences()
    @property
    def drawingViewPreferences(self) -> DrawingViewPreferences:
        """
        Gets view appearance settings. Consider shaded styles for animation views.
        """
        return DrawingViewPreferences()

class AssemblyPreferences(core.Base):
    """
    !!!!! Warning !!!!!
    ! This is in preview state; please see the help for more info
    !!!!! Warning !!!!!
    
    Preferences for assembly sheets (main and sub-assembly). Includes ISO view, orthogonal views, and parts list options.
    The same AssemblyPreferences class is used for both main assembly and sub-assembly configurations.
    """
    def __init__(self):
        pass
    @staticmethod
    def cast(arg) -> AssemblyPreferences:
        return AssemblyPreferences()
    @property
    def isoViewSheetPreferences(self) -> AssemblySheetPreferences:
        """
        Gets settings for the isometric view sheet. Configure parts list inclusion and location.
        """
        return AssemblySheetPreferences()
    @property
    def orthogonalViewSheetPreferences(self) -> AssemblySheetPreferences:
        """
        Gets settings for the orthogonal views sheet. Configure parts list inclusion and location.
        """
        return AssemblySheetPreferences()
    @property
    def autoDimensionPreferences(self) -> AutoDimensionBasePreferences:
        """
        Gets auto-dimension settings (strategy, hole preferences). Requires GlobalPreferences.enableAutoDimension.
        """
        return AutoDimensionBasePreferences()
    @property
    def drawingViewPreferences(self) -> DrawingViewPreferences:
        """
        Gets view appearance settings (style, edges, center marks, center lines).
        """
        return DrawingViewPreferences()

class AssemblySheetPreferences(core.Base):
    """
    !!!!! Warning !!!!!
    ! This is in preview state; please see the help for more info
    !!!!! Warning !!!!!
    
    Preferences for assembly sheet views (both ISO and orthogonal). Configure parts list and view sheet creation.
    Used for both isometric and orthogonal projection sheet configurations.
    Default: Parts list IS included for ISO views, NOT included for orthogonal views.
    """
    def __init__(self):
        pass
    @staticmethod
    def cast(arg) -> AssemblySheetPreferences:
        return AssemblySheetPreferences()
    @property
    def isPartsListIncluded(self) -> bool:
        """
        Gets and sets whether to include a parts list (BOM) on the sheet. Default: true for ISO views, false for orthogonal views.
        Applicable only when isSheetCreated is true.
        """
        return bool()
    @isPartsListIncluded.setter
    def isPartsListIncluded(self, value: bool):
        """
        Gets and sets whether to include a parts list (BOM) on the sheet. Default: true for ISO views, false for orthogonal views.
        Applicable only when isSheetCreated is true.
        """
        pass
    @property
    def partsListLocationType(self) -> TableLocationTypes:
        """
        Gets and sets the corner location for the parts list table. Only applies when isPartsListIncluded is true.
        Default: TopRightTableLocationType for ISO views, TopLeftTableLocationType for orthogonal views.
        """
        return TableLocationTypes()
    @partsListLocationType.setter
    def partsListLocationType(self, value: TableLocationTypes):
        """
        Gets and sets the corner location for the parts list table. Only applies when isPartsListIncluded is true.
        Default: TopRightTableLocationType for ISO views, TopLeftTableLocationType for orthogonal views.
        """
        pass
    @property
    def isSheetCreated(self) -> bool:
        """
        Gets and sets whether to create the view sheet (ISO or orthogonal). Default: true.
        """
        return bool()
    @isSheetCreated.setter
    def isSheetCreated(self, value: bool):
        """
        Gets and sets whether to create the view sheet (ISO or orthogonal). Default: true.
        """
        pass

class AutoDimensionBasePreferences(core.Base):
    """
    !!!!! Warning !!!!!
    ! This is in preview state; please see the help for more info
    !!!!! Warning !!!!!
    
    Base auto-dimension settings: enable, strategy, hole preferences.
    Applicable only when GlobalPreferences.isAutoDimensionEnabled is true.
    """
    def __init__(self):
        pass
    @staticmethod
    def cast(arg) -> AutoDimensionBasePreferences:
        return AutoDimensionBasePreferences()
    @property
    def isAutoDimensionEnabled(self) -> bool:
        """
        Gets and sets whether auto-dimensioning is enabled for this sheet type. Default: true.
        """
        return bool()
    @isAutoDimensionEnabled.setter
    def isAutoDimensionEnabled(self, value: bool):
        """
        Gets and sets whether auto-dimensioning is enabled for this sheet type. Default: true.
        """
        pass
    @property
    def dimensionStrategyType(self) -> DimensionStrategyTypes:
        """
        Gets and sets the dimension placement strategy. Default: OverallDimensionStrategyType.
        """
        return DimensionStrategyTypes()
    @dimensionStrategyType.setter
    def dimensionStrategyType(self, value: DimensionStrategyTypes):
        """
        Gets and sets the dimension placement strategy. Default: OverallDimensionStrategyType.
        """
        pass
    @property
    def holePreferencesType(self) -> HolePreferencesTypes:
        """
        Gets and sets hole and thread annotation preferences. Default: HoleAndThreadNoteHolePreferencesType.
        """
        return HolePreferencesTypes()
    @holePreferencesType.setter
    def holePreferencesType(self, value: HolePreferencesTypes):
        """
        Gets and sets hole and thread annotation preferences. Default: HoleAndThreadNoteHolePreferencesType.
        """
        pass

class AutomationPreferences(core.Base):
    """
    !!!!! Warning !!!!!
    ! This is in preview state; please see the help for more info
    !!!!! Warning !!!!!
    
    Central configuration hub for automatic drawing preferences. Access globalPreferences for sheet
    generation toggles, and type-specific preferences for each sheet type.
    """
    def __init__(self):
        pass
    @staticmethod
    def cast(arg) -> AutomationPreferences:
        return AutomationPreferences()
    @property
    def globalPreferences(self) -> GlobalPreferences:
        """
        Gets GlobalPreferences for sheet generation toggles, auto-dimensioning, and component omission rules.
        """
        return GlobalPreferences()
    @property
    def mainAssemblyPreferences(self) -> AssemblyPreferences:
        """
        Gets preferences for main (top-level) assembly sheets: ISO views, orthogonal views, dimensions, view appearance.
        """
        return AssemblyPreferences()
    @property
    def subAssemblyPreferences(self) -> AssemblyPreferences:
        """
        Gets preferences for sub-assembly sheets: ISO views, orthogonal views, dimensions, view appearance.
        """
        return AssemblyPreferences()
    @property
    def animationPreferences(self) -> AnimationPreferences:
        """
        Gets preferences for animation/exploded view sheets. Enable via GlobalPreferences.generateAnimationSheet.
        """
        return AnimationPreferences()
    @property
    def componentPreferences(self) -> ComponentPreferences:
        """
        Gets preferences for individual component (part) sheets: views, dimensions, view appearance.
        """
        return ComponentPreferences()
    @property
    def foldedModelPreferences(self) -> FoldedModelPreferences:
        """
        Gets preferences for sheet metal folded model sheets (formed state). Complements flat pattern sheets.
        """
        return FoldedModelPreferences()
    @property
    def flatPatternPreferences(self) -> FlatPatternPreferences:
        """
        Gets preferences for sheet metal flat pattern sheets (unfolded state with bend information).
        """
        return FlatPatternPreferences()

class ComponentPreferences(core.Base):
    """
    !!!!! Warning !!!!!
    ! This is in preview state; please see the help for more info
    !!!!! Warning !!!!!
    
    Preferences for individual component (part) sheets with views, dimensions, and annotations.
    """
    def __init__(self):
        pass
    @staticmethod
    def cast(arg) -> ComponentPreferences:
        return ComponentPreferences()
    @property
    def sheetViewPreferences(self) -> ComponentSheetViewPreferences:
        """
        Gets view generation preferences for component sheets. Controls whether orthogonal projection views
        (front, top, right side) are added to the sheet, and whether an optional isometric view is included.
        """
        return ComponentSheetViewPreferences()
    @property
    def autoDimensionPreferences(self) -> AutoDimensionComponentPreferences:
        """
        Gets auto-dimension settings (strategy, origin, patterns). Requires GlobalPreferences.enableAutoDimension.
        """
        return AutoDimensionComponentPreferences()
    @property
    def drawingViewPreferences(self) -> DrawingViewPreferences:
        """
        Gets view appearance settings (style, edges, center marks, center lines).
        """
        return DrawingViewPreferences()

class ComponentSheetViewPreferences(core.Base):
    """
    !!!!! Warning !!!!!
    ! This is in preview state; please see the help for more info
    !!!!! Warning !!!!!
    
    Preferences for component sheet views. Configure orthographic view creation and optional isometric view.
    This class provides settings for controlling which views are generated on component sheets, including
    standard orthographic projections (front, top, right side) and an optional isometric view.
    """
    def __init__(self):
        pass
    @staticmethod
    def cast(arg) -> ComponentSheetViewPreferences:
        return ComponentSheetViewPreferences()
    @property
    def isOrthogonalViewAdded(self) -> bool:
        """
        Gets and sets whether to add orthogonal projection views (front, top, side) for the component.
        When true, the system will automatically generate standard orthographic projection views
        (front, top, and right side views) arranged on the sheet. Default: true.
        """
        return bool()
    @isOrthogonalViewAdded.setter
    def isOrthogonalViewAdded(self, value: bool):
        """
        Gets and sets whether to add orthogonal projection views (front, top, side) for the component.
        When true, the system will automatically generate standard orthographic projection views
        (front, top, and right side views) arranged on the sheet. Default: true.
        """
        pass
    @property
    def isIsometricViewAdded(self) -> bool:
        """
        Gets and sets whether to add an isometric view alongside orthogonal views. Default: false.
        Applicable only when isOrthogonalViewAdded is true.
        """
        return bool()
    @isIsometricViewAdded.setter
    def isIsometricViewAdded(self, value: bool):
        """
        Gets and sets whether to add an isometric view alongside orthogonal views. Default: false.
        Applicable only when isOrthogonalViewAdded is true.
        """
        pass

class CreateDrawingInput(core.Base):
    """
    !!!!! Warning !!!!!
    ! This is in preview state; please see the help for more info
    !!!!! Warning !!!!!
    
    Input parameters for drawing creation. Create via DrawingManager.createDrawingInput().
    """
    def __init__(self):
        pass
    @staticmethod
    def cast(arg) -> CreateDrawingInput:
        return CreateDrawingInput()
    def handler(self, handler: core.DataEventHandler) -> bool:
        """
        Sets the async data event handler for monitoring progress of drawing creation.
        Currently not used as drawing creation is synchronous.
        """
        return bool()
    @property
    def creationMode(self) -> DrawingCreationModes:
        """
        Gets and sets the drawing creation mode. Default: AutomaticDrawingCreationMode.
        """
        return DrawingCreationModes()
    @creationMode.setter
    def creationMode(self, value: DrawingCreationModes):
        """
        Gets and sets the drawing creation mode. Default: AutomaticDrawingCreationMode.
        """
        pass
    @property
    def content(self) -> DrawingContentTypes:
        """
        Gets and sets which assembly content is included for automatic drawing creation:
        full assembly or visible-only. Default: FullAssemblyDrawingContentType.
        """
        return DrawingContentTypes()
    @content.setter
    def content(self, value: DrawingContentTypes):
        """
        Gets and sets which assembly content is included for automatic drawing creation:
        full assembly or visible-only. Default: FullAssemblyDrawingContentType.
        """
        pass
    @property
    def baseDocumentType(self) -> BaseDocumentTypes:
        """
        Gets and sets the base document type option for drawing creation. Specifies whether to create from scratch or from a template.
        Default: FromScratchBaseDocumentType.
        """
        return BaseDocumentTypes()
    @baseDocumentType.setter
    def baseDocumentType(self, value: BaseDocumentTypes):
        """
        Gets and sets the base document type option for drawing creation. Specifies whether to create from scratch or from a template.
        Default: FromScratchBaseDocumentType.
        """
        pass
    @property
    def standard(self) -> DrawingStandardTypes:
        """
        Gets and sets the drawing standard (ISO or ASME). Default: ISODrawingStandardType.
        """
        return DrawingStandardTypes()
    @standard.setter
    def standard(self, value: DrawingStandardTypes):
        """
        Gets and sets the drawing standard (ISO or ASME). Default: ISODrawingStandardType.
        """
        pass
    @property
    def templateFile(self) -> core.DataFile:
        """
        Gets or sets the template file to use when creating the drawing.
        
        / This value is only used when 
        """
        return core.DataFile()
    @templateFile.setter
    def templateFile(self, value: core.DataFile):
        """
        Gets or sets the template file to use when creating the drawing.
        
        / This value is only used when 
        """
        pass
    @property
    def units(self) -> DrawingUnitTypes:
        """
        Gets and sets the drawing units (mm or inch). Default: MillimeterDrawingUnitType.
        """
        return DrawingUnitTypes()
    @units.setter
    def units(self, value: DrawingUnitTypes):
        """
        Gets and sets the drawing units (mm or inch). Default: MillimeterDrawingUnitType.
        """
        pass
    @property
    def sheetSize(self) -> SheetSizes:
        """
        Gets and sets the sheet size. This defaults to A3ISOSheetSize.
        Check the drawing standard via the standard property before setting — ISO sizes (A0–A4) are only
        applicable when the standard is ISO, and ASME sizes (A–E) are only applicable when the standard
        is ASME. Setting a size that does not match the active standard will have no effect.
        To specify a custom sheet size, use the setCustomSheetSize method instead — CustomSheetSize cannot be set directly.
        When the standard is ISO and the sheet size is A0ISOSheetSize, orientation cannot be set to PortraitSheetOrientationType.
        When the standard is ASME and the sheet size is EASMESheetSize, orientation cannot be set to PortraitSheetOrientationType.
        """
        return SheetSizes()
    @sheetSize.setter
    def sheetSize(self, value: SheetSizes):
        """
        Gets and sets the sheet size. This defaults to A3ISOSheetSize.
        Check the drawing standard via the standard property before setting — ISO sizes (A0–A4) are only
        applicable when the standard is ISO, and ASME sizes (A–E) are only applicable when the standard
        is ASME. Setting a size that does not match the active standard will have no effect.
        To specify a custom sheet size, use the setCustomSheetSize method instead — CustomSheetSize cannot be set directly.
        When the standard is ISO and the sheet size is A0ISOSheetSize, orientation cannot be set to PortraitSheetOrientationType.
        When the standard is ASME and the sheet size is EASMESheetSize, orientation cannot be set to PortraitSheetOrientationType.
        """
        pass
    @property
    def customSize(self) -> CustomSheetSize:
        """
        Gets or sets the custom sheet size for the drawing.
        customSize : A 
        Returns 
        """
        return CustomSheetSize()
    @customSize.setter
    def customSize(self, value: CustomSheetSize):
        """
        Gets or sets the custom sheet size for the drawing.
        customSize : A 
        Returns 
        """
        pass
    @property
    def orientationType(self) -> SheetOrientationTypes:
        """
        Gets and sets the sheet orientation. Default: LandscapeSheetOrientationType.
        PortraitSheetOrientationType is not supported when the standard is ISO and sheet size is A0ISOSheetSize,
        or when the standard is ASME and sheet size is EASMESheetSize.
        """
        return SheetOrientationTypes()
    @orientationType.setter
    def orientationType(self, value: SheetOrientationTypes):
        """
        Gets and sets the sheet orientation. Default: LandscapeSheetOrientationType.
        PortraitSheetOrientationType is not supported when the standard is ISO and sheet size is A0ISOSheetSize,
        or when the standard is ASME and sheet size is EASMESheetSize.
        """
        pass
    @property
    def sheetCreationType(self) -> SheetCreationTypes:
        """
        Gets and sets which hierarchy levels get sheets. FirstLevelOnlySheetCreationType reduces file size. Default: AllLevelsSheetCreationType.
        """
        return SheetCreationTypes()
    @sheetCreationType.setter
    def sheetCreationType(self, value: SheetCreationTypes):
        """
        Gets and sets which hierarchy levels get sheets. FirstLevelOnlySheetCreationType reduces file size. Default: AllLevelsSheetCreationType.
        """
        pass
    @property
    def automationPreferences(self) -> AutomationPreferences:
        """
        Gets the AutomationPreferences for configuring global, assembly, component, and sheet metal
        sheet settings. Modifications to the returned object directly affect drawing creation.
        """
        return AutomationPreferences()

class CustomSheetSize(core.Base):
    """
    !!!!! Warning !!!!!
    ! This is in preview state; please see the help for more info
    !!!!! Warning !!!!!
    
    Custom width and height cannot exceed 5000 mm × 5000 mm (millimeter units) or 200 inch × 200 inch (inch units).
    Horizontal and vertical zone counts cannot exceed 1000.
    """
    def __init__(self):
        pass
    @staticmethod
    def cast(arg) -> CustomSheetSize:
        return CustomSheetSize()
    @property
    def width(self) -> float:
        """
        Gets and sets the width of the sheet.
        """
        return float()
    @width.setter
    def width(self, value: float):
        """
        Gets and sets the width of the sheet.
        """
        pass
    @property
    def height(self) -> float:
        """
        Gets and sets the height of the sheet.
        """
        return float()
    @height.setter
    def height(self, value: float):
        """
        Gets and sets the height of the sheet.
        """
        pass
    @property
    def horizontalZones(self) -> int:
        """
        Gets and sets horizontal zones. Minimum 2 for drawing creation.
        """
        return int()
    @horizontalZones.setter
    def horizontalZones(self, value: int):
        """
        Gets and sets horizontal zones. Minimum 2 for drawing creation.
        """
        pass
    @property
    def verticalZones(self) -> int:
        """
        Gets and sets vertical zones. Minimum 2 for drawing creation.
        """
        return int()
    @verticalZones.setter
    def verticalZones(self, value: int):
        """
        Gets and sets vertical zones. Minimum 2 for drawing creation.
        """
        pass

class CustomTableInput(core.Base):
    """
    !!!!! Warning !!!!!
    ! This is in preview state; please see the help for more info
    !!!!! Warning !!!!!
    
    The input object that defines the required input to create a Custom table when using the
    CustomTables.add method. Created using the CustomTables.createInput method.
    """
    def __init__(self):
        pass
    @staticmethod
    def cast(arg) -> CustomTableInput:
        return CustomTableInput()
    @property
    def columnCount(self) -> int:
        """
        Gets and sets the number of columns in the table.
        """
        return int()
    @columnCount.setter
    def columnCount(self, value: int):
        """
        Gets and sets the number of columns in the table.
        """
        pass
    @property
    def rowCount(self) -> int:
        """
        Gets and sets the number of rows in the table. This does not include the header row.
        """
        return int()
    @rowCount.setter
    def rowCount(self, value: int):
        """
        Gets and sets the number of rows in the table. This does not include the header row.
        """
        pass

class CustomTables(core.Base):
    """
    !!!!! Warning !!!!!
    ! This is in preview state; please see the help for more info
    !!!!! Warning !!!!!
    
    Collection object that provides access to all custom tables on a sheet and supports creating new tables.
    Obtained via the Sheet.customTables property.
    """
    def __init__(self):
        pass
    @staticmethod
    def cast(arg) -> CustomTables:
        return CustomTables()
    def __len__(self) -> int:
        return 0
    def __getitem__(self, index: int) -> CustomTable:
        return None
    def __iter__(self) -> Iterator[CustomTable]:
        return None
    def createInput(self) -> CustomTableInput:
        """
        !!!!! Warning !!!!!
        ! This is in preview state; please see the help for more info
        !!!!! Warning !!!!!
        
        Creates a new CustomTableInput object that is used to define the properties needed to create a custom table.
        After configuring the returned input object, pass it to the add method to create the table.
        Returns the newly created CustomTableInput object, or null if creation failed.
        """
        return CustomTableInput()
    def add(self, input: CustomTableInput) -> CustomTable:
        """
        !!!!! Warning !!!!!
        ! This is in preview state; please see the help for more info
        !!!!! Warning !!!!!
        
        Creates a custom table on the sheet based on the provided input settings.
        input : A CustomTableInput object created using the CustomTables.createInput method.
        Returns the newly created CustomTable object or null in the case of failure.
        """
        return CustomTable()

class DrawingExportManager(core.Base):
    """
    Provides support to export the drawing in various formats.
    """
    def __init__(self):
        pass
    @staticmethod
    def cast(arg) -> DrawingExportManager:
        return DrawingExportManager()
    def createPDFExportOptions(self, filename: str) -> PDFExportOptions:
        """
        Defines the various settings for a STEP export.
        filename : The name of the file to export to. Use settings on the returned PDFExportOptions
        object to change other settings.
        Returns a PDFExportOptions object if successful and null if it should fail.
        """
        return PDFExportOptions()
    def execute(self, exportOptions: DrawingExportOptions) -> bool:
        """
        Executes the export operation to create the file in the format specified by the input ExportOptions object.
        exportOptions : A DrawingExportOptions object that is created using one of the create methods on the DrawingExportManager object.
        This defines the type of export and defines the options supported for that file type.
        Returns true if the export was successful.
        """
        return bool()

class DrawingExportOptions(core.Base):
    """
    The base class for the different drawing export types.  This class is never directly used
    in an export because you need the specific export type to specify the type of
    export to be performed.
    """
    def __init__(self):
        pass
    @staticmethod
    def cast(arg) -> DrawingExportOptions:
        return DrawingExportOptions()
    @property
    def filename(self) -> str:
        """
        Gets and sets the filename that the exported file will be written to.
        """
        return str()
    @filename.setter
    def filename(self, value: str):
        """
        Gets and sets the filename that the exported file will be written to.
        """
        pass

class DrawingManager(core.Base):
    """
    !!!!! Warning !!!!!
    ! This is in preview state; please see the help for more info
    !!!!! Warning !!!!!
    
    Application-level drawing functionality. Access via the static get property.
    """
    def __init__(self):
        pass
    @staticmethod
    def cast(arg) -> DrawingManager:
        return DrawingManager()
    @staticmethod
    def get() -> DrawingManager:
        """
        Returns the DrawingManager singleton instance.
        DrawingManager object, or null on failure.
        """
        return DrawingManager()
    def createDrawingInput(self, design: core.DataFile, creationMode: DrawingCreationModes) -> CreateDrawingInput:
        """
        Creates an input object that is used to define all of the settings needed to create a new drawing.
        After editing the returned input object, you can use it as input to a create method to create the new drawing.
        Note: Currently only AutomaticDrawingCreationMode is supported.
        design : DataFile containing the source design.
        creationMode : The drawing creation mode. Only AutomaticDrawingCreationMode is currently supported.
        CreateDrawingInput object, or null on failure.
        """
        return CreateDrawingInput()
    def createDrawing(self, input: CreateDrawingInput) -> core.DataFile:
        """
        Creates an drawing document based on the settings defined in the input object.
        input : A CreateDrawingInput object that was created using the createDrawingInput method on the DrawingManager object.
        DataFile of created drawing, or null on failure.
        """
        return core.DataFile()

class DrawingViewPreferences(core.Base):
    """
    !!!!! Warning !!!!!
    ! This is in preview state; please see the help for more info
    !!!!! Warning !!!!!
    
    Drawing view appearance settings: style, edges, center marks, center lines.
    """
    def __init__(self):
        pass
    @staticmethod
    def cast(arg) -> DrawingViewPreferences:
        return DrawingViewPreferences()
    @property
    def style(self) -> DrawingViewStyleTypes:
        """
        Gets and sets the visual rendering style. Default: VisibleEdgesDrawingViewStyleType.
        """
        return DrawingViewStyleTypes()
    @style.setter
    def style(self, value: DrawingViewStyleTypes):
        """
        Gets and sets the visual rendering style. Default: VisibleEdgesDrawingViewStyleType.
        """
        pass
    @property
    def tangentEdgesType(self) -> TangentEdgeDisplayTypes:
        """
        Gets and sets the tangent edge display mode for the drawing view. Controls how tangent edges
        (edges where two tangent faces meet) are displayed. Default: OffTangentEdgeDisplayType.
        """
        return TangentEdgeDisplayTypes()
    @tangentEdgesType.setter
    def tangentEdgesType(self, value: TangentEdgeDisplayTypes):
        """
        Gets and sets the tangent edge display mode for the drawing view. Controls how tangent edges
        (edges where two tangent faces meet) are displayed. Default: OffTangentEdgeDisplayType.
        """
        pass
    @property
    def isShowInterferenceEdges(self) -> bool:
        """
        Gets and sets whether interference edges are shown in the drawing view. Default: true for standard views, false for flat patterns.
        """
        return bool()
    @isShowInterferenceEdges.setter
    def isShowInterferenceEdges(self, value: bool):
        """
        Gets and sets whether interference edges are shown in the drawing view. Default: true for standard views, false for flat patterns.
        """
        pass
    @property
    def isShowThreadEdges(self) -> bool:
        """
        Gets and sets whether thread representations are shown in the drawing view. Default: true for standard views, false for flat patterns.
        """
        return bool()
    @isShowThreadEdges.setter
    def isShowThreadEdges(self, value: bool):
        """
        Gets and sets whether thread representations are shown in the drawing view. Default: true for standard views, false for flat patterns.
        """
        pass
    @property
    def centerMarkType(self) -> CenterMarkDisplayTypes:
        """
        Gets and sets the center mark display mode for the drawing view. Controls which circular features
        (holes, fillets, punches) display center marks. Default: OffCenterMarkDisplayType.
        """
        return CenterMarkDisplayTypes()
    @centerMarkType.setter
    def centerMarkType(self, value: CenterMarkDisplayTypes):
        """
        Gets and sets the center mark display mode for the drawing view. Controls which circular features
        (holes, fillets, punches) display center marks. Default: OffCenterMarkDisplayType.
        """
        pass
    @property
    def centerLineType(self) -> CenterLineDisplayTypes:
        """
        Gets and sets the center line display mode for the drawing view. Controls which cylindrical features
        (holes, shafts) display center lines. Default: OffCenterLineDisplayType.
        """
        return CenterLineDisplayTypes()
    @centerLineType.setter
    def centerLineType(self, value: CenterLineDisplayTypes):
        """
        Gets and sets the center line display mode for the drawing view. Controls which cylindrical features
        (holes, shafts) display center lines. Default: OffCenterLineDisplayType.
        """
        pass

class FlatPatternOrthogonalViewPreferences(core.Base):
    """
    !!!!! Warning !!!!!
    ! This is in preview state; please see the help for more info
    !!!!! Warning !!!!!
    
    Preferences for flat pattern orthogonal view sheets. Configure folded model view, bend table.
    """
    def __init__(self):
        pass
    @staticmethod
    def cast(arg) -> FlatPatternOrthogonalViewPreferences:
        return FlatPatternOrthogonalViewPreferences()
    @property
    def isFoldedModelIsometricViewAdded(self) -> bool:
        """
        Gets and sets whether to add a folded model isometric view for reference on the flat pattern sheet. Default: false.
        """
        return bool()
    @isFoldedModelIsometricViewAdded.setter
    def isFoldedModelIsometricViewAdded(self, value: bool):
        """
        Gets and sets whether to add a folded model isometric view for reference on the flat pattern sheet. Default: false.
        """
        pass
    @property
    def isBendTableIncluded(self) -> bool:
        """
        Gets and sets whether to include a bend table with manufacturing data on the flat pattern sheet. Default: true.
        """
        return bool()
    @isBendTableIncluded.setter
    def isBendTableIncluded(self, value: bool):
        """
        Gets and sets whether to include a bend table with manufacturing data on the flat pattern sheet. Default: true.
        """
        pass
    @property
    def bendTableLocation(self) -> TableLocationTypes:
        """
        Gets and sets the corner location for the bend table. Only applies when isBendTableIncluded is true. Default: TopLeftTableLocationType.
        """
        return TableLocationTypes()
    @bendTableLocation.setter
    def bendTableLocation(self, value: TableLocationTypes):
        """
        Gets and sets the corner location for the bend table. Only applies when isBendTableIncluded is true. Default: TopLeftTableLocationType.
        """
        pass

class FlatPatternPreferences(core.Base):
    """
    !!!!! Warning !!!!!
    ! This is in preview state; please see the help for more info
    !!!!! Warning !!!!!
    
    Preferences for sheet metal flat pattern sheets (unfolded state with bend information).
    """
    def __init__(self):
        pass
    @staticmethod
    def cast(arg) -> FlatPatternPreferences:
        return FlatPatternPreferences()
    @property
    def orthogonalViewSheetPreferences(self) -> FlatPatternOrthogonalViewPreferences:
        """
        Gets flat pattern sheet settings: folded model view, bend table, table location.
        """
        return FlatPatternOrthogonalViewPreferences()
    @property
    def autoDimensionPreferences(self) -> AutoDimensionComponentPreferences:
        """
        Gets auto-dimension settings (strategy, origin, patterns). Requires GlobalPreferences.enableAutoDimension.
        """
        return AutoDimensionComponentPreferences()
    @property
    def drawingViewPreferences(self) -> DrawingViewFlatPatternPreferences:
        """
        Gets view appearance settings with flat pattern-specific options like bend extents.
        """
        return DrawingViewFlatPatternPreferences()

class FoldedModelPreferences(core.Base):
    """
    !!!!! Warning !!!!!
    ! This is in preview state; please see the help for more info
    !!!!! Warning !!!!!
    
    Preferences for sheet metal folded model sheets (formed state). Complements flat pattern sheets.
    """
    def __init__(self):
        pass
    @staticmethod
    def cast(arg) -> FoldedModelPreferences:
        return FoldedModelPreferences()
    @property
    def sheetViewPreferences(self) -> ComponentSheetViewPreferences:
        """
        Gets view generation preferences for folded model sheets. Controls whether orthogonal projection views
        (front, top, right side) are added to the sheet, and whether an optional isometric view is included.
        """
        return ComponentSheetViewPreferences()
    @property
    def autoDimensionPreferences(self) -> AutoDimensionComponentPreferences:
        """
        Gets auto-dimension settings (strategy, origin, patterns). Requires GlobalPreferences.enableAutoDimension.
        """
        return AutoDimensionComponentPreferences()
    @property
    def drawingViewPreferences(self) -> DrawingViewPreferences:
        """
        Gets view appearance settings (style, edges, center marks, center lines).
        """
        return DrawingViewPreferences()

class GlobalPreferences(core.Base):
    """
    !!!!! Warning !!!!!
    ! This is in preview state; please see the help for more info
    !!!!! Warning !!!!!
    
    Global preferences for drawing generation: sheet toggles, auto-dimensioning, component omission.
    """
    def __init__(self):
        pass
    @staticmethod
    def cast(arg) -> GlobalPreferences:
        return GlobalPreferences()
    @property
    def omitComponentsWithKeywords(self) -> str:
        """
        Gets and sets comma-separated keywords to omit components by name. Default: "Bolt,Screw,Nut,Washer".
        """
        return str()
    @omitComponentsWithKeywords.setter
    def omitComponentsWithKeywords(self, value: str):
        """
        Gets and sets comma-separated keywords to omit components by name. Default: "Bolt,Screw,Nut,Washer".
        """
        pass
    @property
    def isDetectAndOmitFasteners(self) -> bool:
        """
        Gets and sets whether to auto-detect and omit fasteners by geometry. Default: false.
        """
        return bool()
    @isDetectAndOmitFasteners.setter
    def isDetectAndOmitFasteners(self, value: bool):
        """
        Gets and sets whether to auto-detect and omit fasteners by geometry. Default: false.
        """
        pass
    @property
    def isMainAssemblySheetGenerated(self) -> bool:
        """
        Gets and sets whether to generate main assembly sheets. Default: true.
        """
        return bool()
    @isMainAssemblySheetGenerated.setter
    def isMainAssemblySheetGenerated(self, value: bool):
        """
        Gets and sets whether to generate main assembly sheets. Default: true.
        """
        pass
    @property
    def isSubAssemblySheetGenerated(self) -> bool:
        """
        Gets and sets whether to generate sub-assembly sheets. Default: true.
        """
        return bool()
    @isSubAssemblySheetGenerated.setter
    def isSubAssemblySheetGenerated(self, value: bool):
        """
        Gets and sets whether to generate sub-assembly sheets. Default: true.
        """
        pass
    @property
    def isAnimationSheetGenerated(self) -> bool:
        """
        Gets and sets whether to generate animation/exploded view sheets. Default: false.
        """
        return bool()
    @isAnimationSheetGenerated.setter
    def isAnimationSheetGenerated(self, value: bool):
        """
        Gets and sets whether to generate animation/exploded view sheets. Default: false.
        """
        pass
    @property
    def isComponentSheetGenerated(self) -> bool:
        """
        Gets and sets whether to generate component (part) sheets. Default: true.
        """
        return bool()
    @isComponentSheetGenerated.setter
    def isComponentSheetGenerated(self, value: bool):
        """
        Gets and sets whether to generate component (part) sheets. Default: true.
        """
        pass
    @property
    def isFoldedModelSheetGenerated(self) -> bool:
        """
        Gets and sets whether to generate folded model sheets for sheet metal. Default: true.
        """
        return bool()
    @isFoldedModelSheetGenerated.setter
    def isFoldedModelSheetGenerated(self, value: bool):
        """
        Gets and sets whether to generate folded model sheets for sheet metal. Default: true.
        """
        pass
    @property
    def isFlatPatternSheetGenerated(self) -> bool:
        """
        Gets and sets whether to generate flat pattern sheets for sheet metal. Default: true.
        """
        return bool()
    @isFlatPatternSheetGenerated.setter
    def isFlatPatternSheetGenerated(self, value: bool):
        """
        Gets and sets whether to generate flat pattern sheets for sheet metal. Default: true.
        """
        pass
    @property
    def isAutoDimensionEnabled(self) -> bool:
        """
        Gets and sets whether to enable auto-dimensioning on generated views. Default: true.
        """
        return bool()
    @isAutoDimensionEnabled.setter
    def isAutoDimensionEnabled(self, value: bool):
        """
        Gets and sets whether to enable auto-dimensioning on generated views. Default: true.
        """
        pass

class Sheet(core.Base):
    """
    !!!!! Warning !!!!!
    ! This is in preview state; please see the help for more info
    !!!!! Warning !!!!!
    
    Object that represents the sheet specific data within a drawing document.
    """
    def __init__(self):
        pass
    @staticmethod
    def cast(arg) -> Sheet:
        return Sheet()
    @property
    def customTables(self) -> CustomTables:
        """
        Returns the CustomTables collection for this sheet. Use this collection
        to access existing custom tables or create new ones.
        """
        return CustomTables()

class Table(core.Base):
    """
    !!!!! Warning !!!!!
    ! This is in preview state; please see the help for more info
    !!!!! Warning !!!!!
    
    Base class for all table objects in a drawing.
    """
    def __init__(self):
        pass
    @staticmethod
    def cast(arg) -> Table:
        return Table()
    @property
    def columnCount(self) -> int:
        """
        Returns the number of columns in the table.
        """
        return int()
    @property
    def rowCount(self) -> int:
        """
        Returns the number of rows in the table. This does not include the header row.
        """
        return int()

class AutoDimensionComponentPreferences(AutoDimensionBasePreferences):
    """
    !!!!! Warning !!!!!
    ! This is in preview state; please see the help for more info
    !!!!! Warning !!!!!
    
    Auto-dimension settings for components. Extends base with origin and pattern options.
    """
    def __init__(self):
        pass
    @staticmethod
    def cast(arg) -> AutoDimensionComponentPreferences:
        return AutoDimensionComponentPreferences()
    @property
    def defaultOriginType(self) -> DefaultOriginTypes:
        """
        Gets and sets the datum origin for dimension placement. Default: ModelOriginDefaultOriginType.
        """
        return DefaultOriginTypes()
    @defaultOriginType.setter
    def defaultOriginType(self, value: DefaultOriginTypes):
        """
        Gets and sets the datum origin for dimension placement. Default: ModelOriginDefaultOriginType.
        """
        pass
    @property
    def isCircularPatternDimensionsIncluded(self) -> bool:
        """
        Gets and sets whether to include dimensions for circular pattern features. Default: true.
        """
        return bool()
    @isCircularPatternDimensionsIncluded.setter
    def isCircularPatternDimensionsIncluded(self, value: bool):
        """
        Gets and sets whether to include dimensions for circular pattern features. Default: true.
        """
        pass

class CustomTable(Table):
    """
    !!!!! Warning !!!!!
    ! This is in preview state; please see the help for more info
    !!!!! Warning !!!!!
    
    Represents a custom table on a drawing sheet.
    """
    def __init__(self):
        pass
    @staticmethod
    def cast(arg) -> CustomTable:
        return CustomTable()
    def setCellData(self, rowIndex: int, coulmnIndex: int, data: str) -> bool:
        """
        Updates the content of a specific cell in the custom table.
        rowIndex : The zero-based row index of the cell to update.
        columnIndex : The zero-based column index of the cell to update.
        data : The string data to set in the specified cell.
        Returns true if the content is modified successfully, otherwise returns false.
        """
        return bool()

class Drawing(core.Product):
    """
    Object that represents the drawing specific data within a drawing document.
    """
    def __init__(self):
        pass
    @staticmethod
    def cast(arg) -> Drawing:
        return Drawing()
    @property
    def exportManager(self) -> DrawingExportManager:
        """
        Returns the DrawingExportManager for this drawing.  You use the ExportManager
        to export the drawing in various formats.
        """
        return DrawingExportManager()
    @property
    def activeSheet(self) -> Sheet:
        """
        !!!!! Warning !!!!!
        ! This is in preview state; please see the help for more info
        !!!!! Warning !!!!!
        
        Returns the current sheet i.e, the active sheet
        """
        return Sheet()

class DrawingDocument(core.Document):
    """
    Object that represents a Fusion 360 drawing document.
    """
    def __init__(self):
        pass
    @staticmethod
    def cast(arg) -> DrawingDocument:
        return DrawingDocument()
    @property
    def drawing(self) -> Drawing:
        """
        Returns the Drawing product object associated with this drawing document.
        """
        return Drawing()

class DrawingViewFlatPatternPreferences(DrawingViewPreferences):
    """
    !!!!! Warning !!!!!
    ! This is in preview state; please see the help for more info
    !!!!! Warning !!!!!
    
    Drawing view settings for flat patterns. Adds bend extents. Different defaults than base.
    """
    def __init__(self):
        pass
    @staticmethod
    def cast(arg) -> DrawingViewFlatPatternPreferences:
        return DrawingViewFlatPatternPreferences()
    @property
    def isShowBendExtents(self) -> bool:
        """
        Gets and sets whether bend extent lines are displayed. Default: true.
        """
        return bool()
    @isShowBendExtents.setter
    def isShowBendExtents(self, value: bool):
        """
        Gets and sets whether bend extent lines are displayed. Default: true.
        """
        pass

class PDFExportOptions(DrawingExportOptions):
    """
    Defines the inputs needed to export the drawing as PDF.
    """
    def __init__(self):
        pass
    @staticmethod
    def cast(arg) -> PDFExportOptions:
        return PDFExportOptions()
    @property
    def sheetsToExport(self) -> PDFSheetsExport:
        """
        Defines which sheets to export.  Defaults to AllPDFSheets which
        will create a single PDF file containing all sheets in the drawing.
        
        the SelectedPDFSheets and CurrentPDFSheet options are dependent on
        the current selections in the user interface.
        
        To set this to RangePDFSheets, use the sheetRange property to define
        the range of sheets to print.
        """
        return PDFSheetsExport()
    @sheetsToExport.setter
    def sheetsToExport(self, value: PDFSheetsExport):
        """
        Defines which sheets to export.  Defaults to AllPDFSheets which
        will create a single PDF file containing all sheets in the drawing.
        
        the SelectedPDFSheets and CurrentPDFSheet options are dependent on
        the current selections in the user interface.
        
        To set this to RangePDFSheets, use the sheetRange property to define
        the range of sheets to print.
        """
        pass
    @property
    def sheetRange(self) -> str:
        """
        Defines the range of sheets to export. This can be a string like
        "1-3" or "1-2,5" where you can define a range of sheets and also
        specific sheets. Setting this property will automatically set
        the sheetsToExport setting to SelectedPDFSheets.
        """
        return str()
    @sheetRange.setter
    def sheetRange(self, value: str):
        """
        Defines the range of sheets to export. This can be a string like
        "1-3" or "1-2,5" where you can define a range of sheets and also
        specific sheets. Setting this property will automatically set
        the sheetsToExport setting to SelectedPDFSheets.
        """
        pass
    @property
    def openPDF(self) -> bool:
        """
        Specifies that the PDF file will be opened after export.
        """
        return bool()
    @openPDF.setter
    def openPDF(self, value: bool):
        """
        Specifies that the PDF file will be opened after export.
        """
        pass
    @property
    def useLineWeights(self) -> bool:
        """
        Specifies if line weights should be used in the exported PDF file.
        """
        return bool()
    @useLineWeights.setter
    def useLineWeights(self, value: bool):
        """
        Specifies if line weights should be used in the exported PDF file.
        """
        pass
